
export default new Map([
["src/content/advanced/hooks-and-automation.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fadvanced%2Fhooks-and-automation.mdx&astroContentModuleFlag=true")],
["src/content/advanced/mcp-external-tools.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fadvanced%2Fmcp-external-tools.mdx&astroContentModuleFlag=true")],
["src/content/advanced/project-configuration.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fadvanced%2Fproject-configuration.mdx&astroContentModuleFlag=true")],
["src/content/advanced/skills-and-workflows.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fadvanced%2Fskills-and-workflows.mdx&astroContentModuleFlag=true")],
["src/content/advanced/subagents-and-parallelization.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fadvanced%2Fsubagents-and-parallelization.mdx&astroContentModuleFlag=true")],
["src/content/foundations/how-tools-work.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Ffoundations%2Fhow-tools-work.mdx&astroContentModuleFlag=true")],
["src/content/foundations/permissions-and-safety.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Ffoundations%2Fpermissions-and-safety.mdx&astroContentModuleFlag=true")],
["src/content/foundations/tool-landscape.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Ffoundations%2Ftool-landscape.mdx&astroContentModuleFlag=true")],
["src/content/foundations/understanding-context.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Ffoundations%2Funderstanding-context.mdx&astroContentModuleFlag=true")],
["src/content/mastery/claude-code.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fmastery%2Fclaude-code.mdx&astroContentModuleFlag=true")],
["src/content/mastery/github-copilot.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fmastery%2Fgithub-copilot.mdx&astroContentModuleFlag=true")],
["src/content/mastery/opencode.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fmastery%2Fopencode.mdx&astroContentModuleFlag=true")],
["src/content/productivity/context-management.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fproductivity%2Fcontext-management.mdx&astroContentModuleFlag=true")],
["src/content/productivity/effective-prompting.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fproductivity%2Feffective-prompting.mdx&astroContentModuleFlag=true")],
["src/content/productivity/explore-plan-build.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fproductivity%2Fexplore-plan-build.mdx&astroContentModuleFlag=true")],
["src/content/productivity/verification-driven-dev.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fproductivity%2Fverification-driven-dev.mdx&astroContentModuleFlag=true")],
["src/content/reference/claude-code-cheatsheet.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Freference%2Fclaude-code-cheatsheet.mdx&astroContentModuleFlag=true")],
["src/content/reference/copilot-cheatsheet.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Freference%2Fcopilot-cheatsheet.mdx&astroContentModuleFlag=true")],
["src/content/reference/opencode-cheatsheet.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Freference%2Fopencode-cheatsheet.mdx&astroContentModuleFlag=true")],
["src/content/reference/tool-comparison.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Freference%2Ftool-comparison.mdx&astroContentModuleFlag=true")]]);
		